// { status: 200,
//     statusText: 'OK',
//     headers:
//      { server: 'ngx_openresty',
//        date: 'Sun, 02 Dec 2018 21:44:40 GMT',
//        'content-type': 'application/json;charset=UTF-8',
//        'transfer-encoding': 'chunked',
//        connection: 'close',
//        vary: 'Accept-Encoding, Accept-Encoding, accept-encoding',
//        'set-cookie': [ 'route=d3bd1ee679a8778c95764f17184e2327; Path=/' ],
//        'cache-control': 'private',
//        expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
//        'x-served-by': 'ip-10-91-250-3/10.91.250.3' },
//     config:
//      { adapter: [Function: httpAdapter],
//        transformRequest: { '0': [Function: transformRequest] },
//        transformResponse: { '0': [Function: transformResponse] },
//        timeout: 0,
//        xsrfCookieName: 'XSRF-TOKEN',
//        xsrfHeaderName: 'X-XSRF-TOKEN',
//        maxContentLength: -1,
//        validateStatus: [Function: validateStatus],
//        headers:
//         { Accept: 'application/json, text/plain, */*',
//           'User-Agent': 'axios/0.18.0' },
//        method: 'get',
//        url: 'https://api.edamam.com/search?q=Pasta+Cheese+chicken&app_id=8417f32f&app_key=cdc0b36554522a88a0242b7ea30e9837&from=0&to=5',
//        data: undefined },
//     request:
//      ClientRequest {
//        domain: null,
//        _events:
//         { socket: [Function],
//           abort: [Function],
//           aborted: [Function],
//           error: [Function],
//           timeout: [Function],
//           prefinish: [Function: requestOnPrefinish] },
//        _eventsCount: 6,
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        outputSize: 0,
//        writable: true,
//        _last: true,
//        upgrading: false,
//        chunkedEncoding: false,
//        shouldKeepAlive: false,
//        useChunkedEncodingByDefault: false,
//        sendDate: false,
//        _removedConnection: false,
//        _removedContLen: false,
//        _removedTE: false,
//        _contentLength: 0,
//        _hasBody: true,
//        _trailer: '',
//        finished: true,
//        _headerSent: true,
//        socket:
//         TLSSocket {
//           _tlsOptions: [Object],
//           _secureEstablished: true,
//           _securePending: false,
//           _newSessionPending: false,
//           _controlReleased: true,
//           _SNICallback: null,
//           servername: 'api.edamam.com',
//           npnProtocol: undefined,
//           alpnProtocol: false,
//           authorized: true,
//           authorizationError: null,
//           encrypted: true,
//           _events: [Object],
//           _eventsCount: 9,
//           connecting: false,
//           _hadError: false,
//           _handle: [Object],
//           _parent: null,
//           _host: 'api.edamam.com',
//           _readableState: [Object],
//           readable: true,
//           domain: null,
//           _maxListeners: undefined,
//           _writableState: [Object],
//           writable: false,
//           allowHalfOpen: false,
//           _bytesDispatched: 226,
//           _sockname: null,
//           _pendingData: null,
//           _pendingEncoding: '',
//           server: undefined,
//           _server: null,
//           ssl: [Object],
//           _requestCert: true,
//           _rejectUnauthorized: true,
//           parser: null,
//           _httpMessage: [Circular],
//           [Symbol(asyncId)]: 177,
//           [Symbol(bytesRead)]: 0 },
//        connection:
//         TLSSocket {
//           _tlsOptions: [Object],
//           _secureEstablished: true,
//           _securePending: false,
//           _newSessionPending: false,
//           _controlReleased: true,
//           _SNICallback: null,
//           servername: 'api.edamam.com',
//           npnProtocol: undefined,
//           alpnProtocol: false,
//           authorized: true,
//           authorizationError: null,
//           encrypted: true,
//           _events: [Object],
//           _eventsCount: 9,
//           connecting: false,
//           _hadError: false,
//           _handle: [Object],
//           _parent: null,
//           _host: 'api.edamam.com',
//           _readableState: [Object],
//           readable: true,
//           domain: null,
//           _maxListeners: undefined,
//           _writableState: [Object],
//           writable: false,
//           allowHalfOpen: false,
//           _bytesDispatched: 226,
//           _sockname: null,
//           _pendingData: null,
//           _pendingEncoding: '',
//           server: undefined,
//           _server: null,
//           ssl: [Object],
//           _requestCert: true,
//           _rejectUnauthorized: true,
//           parser: null,
//           _httpMessage: [Circular],
//           [Symbol(asyncId)]: 177,
//           [Symbol(bytesRead)]: 0 },
//        _header: 'GET /search?q=Pasta+Cheese+chicken&app_id=8417f32f&app_key=cdc0b36554522a88a0242b7ea30e9837&from=0&to=5 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: api.edamam.com\r\nConnection: close\r\n\r\n',
//        _onPendingData: [Function: noopPendingOutput],
//        agent:
//         Agent {
//           domain: null,
//           _events: [Object],
//           _eventsCount: 1,
//           _maxListeners: undefined,
//           defaultPort: 443,
//           protocol: 'https:',
//           options: [Object],
//           requests: {},
//           sockets: [Object],
//           freeSockets: {},
//           keepAliveMsecs: 1000,
//           keepAlive: false,
//           maxSockets: Infinity,
//           maxFreeSockets: 256,
//           maxCachedSessions: 100,
//           _sessionCache: [Object] },
//        socketPath: undefined,
//        timeout: undefined,
//        method: 'GET',
//        path: '/search?q=Pasta+Cheese+chicken&app_id=8417f32f&app_key=cdc0b36554522a88a0242b7ea30e9837&from=0&to=5',
//        _ended: true,
//        res:
//         IncomingMessage {
//           _readableState: [Object],
//           readable: false,
//           domain: null,
//           _events: [Object],
//           _eventsCount: 3,
//           _maxListeners: undefined,
//           socket: [Object],
//           connection: [Object],
//           httpVersionMajor: 1,
//           httpVersionMinor: 1,
//           httpVersion: '1.1',
//           complete: true,
//           headers: [Object],
//           rawHeaders: [Array],
//           trailers: {},
//           rawTrailers: [],
//           upgrade: false,
//           url: '',
//           method: null,
//           statusCode: 200,
//           statusMessage: 'OK',
//           client: [Object],
//           _consuming: true,
//           _dumped: false,
//           req: [Circular],
//           responseUrl: 'https://api.edamam.com/search?q=Pasta+Cheese+chicken&app_id=8417f32f&app_key=cdc0b36554522a88a0242b7ea30e9837&from=0&to=5',
//           redirects: [],
//           read: [Function] },
//        aborted: undefined,
//        timeoutCb: null,
//        upgradeOrConnect: false,
//        parser: null,
//        maxHeadersCount: null,
//        _redirectable:
//         Writable {
//           _writableState: [Object],
//           writable: true,
//           domain: null,
//           _events: [Object],
//           _eventsCount: 2,
//           _maxListeners: undefined,
//           _options: [Object],
//           _redirectCount: 0,
//           _redirects: [],
//           _requestBodyLength: 0,
//           _requestBodyBuffers: [],
//           _onNativeResponse: [Function],
//           _currentRequest: [Circular],
//           _currentUrl: 'https://api.edamam.com/search?q=Pasta+Cheese+chicken&app_id=8417f32f&app_key=cdc0b36554522a88a0242b7ea30e9837&from=0&to=5' },
//        [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
//     data:
//      { q: 'Pasta Cheese chicken',
//        from: 0,
//        to: 5,
//        params:
//         { sane: [],
//           q: [Array],
//           from: [Array],
//           app_key: [Array],
//           to: [Array],
//           app_id: [Array] },
//        more: true,
//        count: 7371,
//        hits: [ [Object], [Object], [Object], [Object], [Object] ] 
//      } 
// }